Migrate model plugin API and compiler to onos-config
onosproject/onos-config pull request #1372
Opened 2021-11-04 02:12 UTC by kuujo

2021-11-04 17:28 UTC, tomikazi approved these changes

2021-11-05 10:28 UTC, SeanCondon commented on model/registry/registry.go
> +func GetPath(dir, target, replace string) (string, error) {
this was unused in the old version

2021-11-05 10:31 UTC, SeanCondon commented on test/model/test@2020-11-18.yang
> +    "Adib Rastegarnia";
I wrote this !

2021-11-05 10:33 UTC, SeanCondon approved these changes

2021-11-08 22:55 UTC, tomikazi approved these changes

2021-11-09 16:42 UTC, ray-milkey requested changes

2021-11-09 16:42 UTC, ray-milkey commented on Makefile
> +	kind load docker-image --name ${KIND_CLUSTER_NAME} ${DOCKER_REPOSITORY}config-model-registry:${ONOS_CONFIG_VERSION}
You'll need to make a corresponding change to build/bin/push-images to publish the new image

2021-11-09 16:42 UTC, ray-milkey commented on Makefile
You'll have to add the new image to the publish target:

./../build-tools/publish-version ${VERSION} onosproject/config-model-registry

2021-12-08 18:26 UTC, kuujo commented
Superseded by sidecar based plugins

2021-12-08 18:26 UTC, closed without merging