Initial NB implementation
onosproject/onos-config pull request #1417
Opened 2022-01-20 20:07 UTC by adibrastegarnia

2022-01-21 19:23 UTC, adibrastegarnia commented
retest this please

2022-01-22 02:31 UTC, kuujo requested changes

2022-01-22 02:31 UTC, kuujo commented on pkg/northbound/gnmi/v2/set.go
> +	ch := make(chan configapi.TransactionEvent)
We should use `WithTransactionID` here to limit the `Watch` events only to those related to this particular transaction.

2022-01-22 21:07 UTC, kuujo approved these changes

2022-01-22 21:09 UTC, merged