Apply validation on the whole config tree path/values
onosproject/onos-config pull request #1453
Opened 2022-01-27 19:01 UTC by adibrastegarnia

2022-01-27 19:34 UTC, ray-milkey approved these changes

2022-01-28 20:13 UTC, kuujo requested changes

2022-01-28 20:13 UTC, kuujo commented on pkg/controller/transaction/controller.go
> +		for _, pathValue := range currentConfigValues {
I would move the definition of `pathValues` down here

2022-01-28 20:14 UTC, kuujo commented on pkg/controller/transaction/controller.go
> +		if config.GetValues() != nil {
I think you can/should just use `config.Values`. The `GetValues()` method is really just there so you can define interfaces for your Protobuf generated types to implement.

2022-01-28 20:16 UTC, kuujo commented on pkg/controller/transaction/controller.go
> +			currentConfigValues[path] = &configapi.PathValue{
I think this should just be called `configValues` because it’s not just current values… it’s the current values plus we’re adding the new ones here.

2022-01-28 20:17 UTC, kuujo commented on pkg/controller/transaction/controller.go
> +			currentConfigValues[path] = &configapi.PathValue{
More descriptive might be to call this `pathValues` (since it’s a path to value mapping) and the other one just `values`.

2022-01-28 20:48 UTC, kuujo approved these changes

2022-01-28 20:51 UTC, merged